services:
  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medic
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pharmasetu-net

  backend:
    image: staycool18/pharmasetu-backend:latest
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8083:8083"
    networks:
      - pharmasetu-net

  frontend:
    image: staycool18/pharmasetu-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - pharmasetu-net

networks:
  pharmasetu-net:
    driver: bridge

volumes:
  mysql_data:
